import type { TacticsProfession, TacticsSkill } from '../model/tactics-model'
export const tacticsSkills: TacticsSkill[] = [
  { id: 'bulwark', name: '壁垒本能', kind: 'passive', baseWeight: 0, effect: 'defense', value: 2 }, { id: 'skirmish', name: '游击本能', kind: 'passive', baseWeight: 0, effect: 'evasion', value: 12 },
  { id: 'ward', name: '守护屏障', kind: 'passive', baseWeight: 100, survivals: ['shield'], effect: 'shield', value: 5 }, { id: 'renewal', name: '复苏', kind: 'passive', baseWeight: 100, survivals: ['regeneration'], effect: 'regeneration', value: 2 }, { id: 'dodge', name: '轻步', kind: 'passive', baseWeight: 100, survivals: ['evasion'], effect: 'evasion', value: 15 }, { id: 'guard', name: '坚守', kind: 'passive', baseWeight: 100, survivals: ['defense'], effect: 'defense', value: 2 }, { id: 'leech', name: '汲取', kind: 'passive', baseWeight: 100, survivals: ['lifesteal'], effect: 'lifesteal', value: 20 }, { id: 'immunity', name: '免疫护符', kind: 'passive', baseWeight: 100, survivals: ['immunity'], effect: 'immunity', value: 1 },
  { id: 'strike', name: '强击', kind: 'active', slot: 'main', energyCost: 2, duration: 0, friendlyFire: false, baseWeight: 100, focuses: ['damage'], effect: 'damage', value: 4, range: 1 }, { id: 'bleeding-edge', name: '裂伤', kind: 'active', slot: 'secondary', energyCost: 0, duration: 2, friendlyFire: false, baseWeight: 100, focuses: ['damage'], effect: 'bleed', value: 2 }, { id: 'mend', name: '治疗术', kind: 'active', slot: 'main', energyCost: 2, duration: 0, friendlyFire: false, baseWeight: 100, focuses: ['healing'], effect: 'heal', value: 6, range: 2 }, { id: 'rally', name: '号令', kind: 'active', slot: 'main', energyCost: 2, duration: 1, friendlyFire: false, baseWeight: 100, focuses: ['buff'], effect: 'buff', value: 2, range: 2 },
]
export const tacticsProfessions: TacticsProfession[] = [
  { id: 'assassin', name: '刺客', attackStyle: 'melee', hasSummonKit: false, damageType: 'physical', skillFocus: 'damage', survivalFocus: 'evasion', passiveSkillId: 'skirmish', energy: { max: 5, regen: 0, name: '体力', color: '#fb7185' }, initialAttributes: { strength: 7, technique: 5, agility: 8, constitution: 4, perception: 2, willpower: 2 }, attributeGrowthWeights: { strength: 4, technique: 3, agility: 5, constitution: 2, perception: 1, willpower: 1 } }, { id: 'raider-cavalry', name: '掠袭骑兵', attackStyle: 'ranged', hasSummonKit: false, damageType: 'physical', skillFocus: 'damage', survivalFocus: 'evasion', passiveSkillId: 'skirmish', energy: { max: 5, regen: 0, name: '体力', color: '#fb7185' }, initialAttributes: { strength: 6, technique: 7, agility: 6, constitution: 5, perception: 2, willpower: 2 }, attributeGrowthWeights: { strength: 4, technique: 5, agility: 3, constitution: 2, perception: 1, willpower: 1 } }, { id: 'crossbowman', name: '重弩手', attackStyle: 'ranged', hasSummonKit: false, damageType: 'physical', skillFocus: 'damage', survivalFocus: 'defense', passiveSkillId: 'bulwark', energy: { max: 5, regen: 0, name: '体力', color: '#fb7185' }, initialAttributes: { strength: 8, technique: 7, agility: 3, constitution: 6, perception: 2, willpower: 2 }, attributeGrowthWeights: { strength: 5, technique: 4, agility: 1, constitution: 3, perception: 1, willpower: 1 } }, { id: 'adept', name: '见习者', attackStyle: 'melee', hasSummonKit: false, damageType: 'physical', skillFocus: 'damage', survivalFocus: 'regeneration', passiveSkillId: 'renewal', energy: { max: 5, regen: 0, name: '体力', color: '#fb7185' }, initialAttributes: { strength: 5, technique: 5, agility: 5, constitution: 5, perception: 5, willpower: 5 }, attributeGrowthWeights: { strength: 1, technique: 1, agility: 1, constitution: 1, perception: 1, willpower: 1 } },
  { id: 'arcanist', name: '奥术术士', attackStyle: 'ranged', hasSummonKit: false, damageType: 'magic', skillFocus: 'damage', survivalFocus: 'shield', passiveSkillId: 'ward', energy: { max: 5, regen: 1, name: '魔能', color: '#60a5fa' }, initialAttributes: { strength: 2, technique: 4, agility: 3, constitution: 4, perception: 9, willpower: 6 }, attributeGrowthWeights: { strength: 1, technique: 2, agility: 1, constitution: 2, perception: 5, willpower: 3 } },
  { id: 'psionic-medic', name: '灵能医师', attackStyle: 'ranged', hasSummonKit: false, damageType: 'psionic', skillFocus: 'healing', survivalFocus: 'evasion', passiveSkillId: 'dodge', energy: { max: 5, regen: 1, name: '念力', color: '#c084fc' }, initialAttributes: { strength: 2, technique: 3, agility: 6, constitution: 6, perception: 4, willpower: 9 }, attributeGrowthWeights: { strength: 1, technique: 1, agility: 3, constitution: 3, perception: 2, willpower: 5 } },
  { id: 'templar-guard', name: '圣堂卫士', attackStyle: 'melee', hasSummonKit: false, damageType: 'physical', skillFocus: 'buff', survivalFocus: 'defense', passiveSkillId: 'guard', energy: { max: 5, regen: 2, name: '体力', color: '#fb7185' }, initialAttributes: { strength: 8, technique: 3, agility: 3, constitution: 9, perception: 3, willpower: 5 }, attributeGrowthWeights: { strength: 4, technique: 1, agility: 1, constitution: 5, perception: 1, willpower: 3 } },
]
export const professionById = (id: string) => tacticsProfessions.find((item) => item.id === id)
export const skillById = (id: string) => tacticsSkills.find((item) => item.id === id)
export const skillWeight = (profession: TacticsProfession, skill: TacticsSkill) => skill.baseWeight + (skill.attackStyles?.includes(profession.attackStyle) ? 20 : 0) + (skill.damageTypes?.includes(profession.damageType) ? 20 : 0) + (skill.focuses?.includes(profession.skillFocus) ? 50 : 0) + (skill.survivals?.includes(profession.survivalFocus) ? 50 : 0)
